[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "semantic_html"
version = "0.1.0"
dependencies = [
    "bleach >= 5.0.0",
    "beautifulsoup4 >= 4.12.0",
    "lxml >= 4.9.0"
]